name: Composite Action

on:
  workflow_dispatch:
    inputs:
      name: 
        description: 'Enter your name'
        required: true
        default: 'Unamed'

jobs:
  composite-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

    
      - name: Call Composite Action
        id: greet
        uses: ./
        with:
          who-to-greet: ${{ github.event.inputs.name }}

      - name: Print Greeting Message
        run: |
          echo "${{ steps.greet.outputs.message }}"    