name: Composite Action

on:
  workflow_dispatch:
   Inputs:
    name:
      description: 'Your name'
      required: true
      default: 'World'

jobs:
  composite-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

    
      - name: Call Composite Action
        id: greet
        uses: ./
        with:
          who-to-greet: ${{ github.event.inputs.name }}

      - name: Print Greeting Message
        run: |
          echo "${{ steps.greet.outputs.message }}"    