name: Script Workflow
on:
  workflow_dispatch:

jobs:
  script-workflow:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Script Workflow 
        run: |
          echo "Hello Script Workflow"
          echo "This is a script workflow example"  
          
      - name: Run a script
        run: |
          python script.py
